import "dotenv/config";
import { defineConfig } from '@prisma/nextjs-config';
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
